modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/verclient/issues"

[[mods]]
modId="verclient"
version="${mod_version}"
displayName="Verclient"
logoFile="logo.png"
credits="VerclientDev"
authors="VerclientDev"
description='''
A custom utility client mod.
'''

[[dependencies.verclient]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.verclient]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
